var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};
$jscomp.getConstructImplementation=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=$jscomp.objectCreate(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||
e}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};$jscomp.polyfill("Reflect",function(a){return a?a:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(a){return $jscomp.construct},"es6","es3");
$jscomp.polyfill("Reflect.setPrototypeOf",function(a){if(a)return a;if($jscomp.setPrototypeOf){var b=$jscomp.setPrototypeOf;return function(c,d){try{return b(c,d),!0}catch(e){return!1}}}return null},"es6","es5");$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,f){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");function projection(a,b,c){return[2/a,0,0,0,0,-2/b,0,0,0,0,2/(void 0===c?400:c),0,-1,1,0,1]}function identity(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}
function translation(a){return[1,0,0,0,0,1,0,0,0,0,1,0,a[0],a[1],a[2],1]}function translate(a,b){return multiply(a,translation(b))}function moveto(a,b){a[12]=0;a[13]=0;a[14]=0;return translate(a,b)}function rotateZ(a,b){var c=degToRad(b);b=Math.cos(c);c=Math.sin(c);return multiply(a,[b,c,0,0,-c,b,0,0,0,0,1,0,0,0,0,1])}function degToRad(a){return a*Math.PI/180}function scale(a,b){return multiply(a,[b[0],0,0,0,0,b[1],0,0,0,0,b[2],0,0,0,0,1])}
function multiply(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],p=a[5],k=a[6],m=a[7],h=a[8],l=a[9],n=a[10],q=a[11],r=a[12],t=a[13],u=a[14];a=a[15];var v=b[0],w=b[1],x=b[2],y=b[3],z=b[4],A=b[5],B=b[6],C=b[7],D=b[8],E=b[9],F=b[10],G=b[11],H=b[12],I=b[13],J=b[14];b=b[15];return[v*c+w*g+x*h+y*r,v*d+w*p+x*l+y*t,v*e+w*k+x*n+y*u,v*f+w*m+x*q+y*a,z*c+A*g+B*h+C*r,z*d+A*p+B*l+C*t,z*e+A*k+B*n+C*u,z*f+A*m+B*q+C*a,D*c+E*g+F*h+G*r,D*d+E*p+F*l+G*t,D*e+E*k+F*n+G*u,D*f+E*m+F*q+G*a,H*c+I*g+J*h+b*r,H*d+I*p+J*l+b*t,H*e+
I*k+J*n+b*u,H*f+I*m+J*q+b*a]}function multiplyM(a,b,c,d){for(var e=[],f=0;f<b;f++)for(var g=0;g<d;g++)e.push(a[f*b]*c[g]+a[f*b+1]*c[g+d]+a[f*b+2]*c[g+2*d]+a[f*b+3]*c[g+3*d]);return e};var fShader="\nprecision mediump float;\nvarying vec4 vColor;\nvoid main(){\n    gl_FragColor = vColor;\n}";var vShader="\nattribute vec4 aPosition;\nuniform vec4 uColor;\nuniform mat4 uProjMatrix;\nuniform mat4 uMatrix;\nvarying vec4 vColor;\nvoid main(){\n    gl_Position = uProjMatrix * uMatrix * aPosition;\n    vColor = uColor;\n}";var Shader=function(a,b,c){a=this.createShader(gl.VERTEX_SHADER,a);b=this.createShader(gl.FRAGMENT_SHADER,b);if(!a||!b)return null;var d=gl.createProgram();gl.attachShader(d,a);gl.attachShader(d,b);c.forEach(function(e,f){gl.bindAttribLocation(d,f,e)});gl.linkProgram(d);this.program=d};
Shader.prototype.createShader=function(a,b){var c=gl.createShader(a);gl.shaderSource(c,b);gl.compileShader(c);return gl.getShaderParameter(c,gl.COMPILE_STATUS)?c:(b=gl.getShaderInfoLog(c),console.error("Shader createShader() Error: Failed to compile "+a+". "+b),gl.deleteShader(c),null)};Shader.prototype.bindAttrib=function(a,b,c,d){gl.bindBuffer(gl.ARRAY_BUFFER,a);gl.enableVertexAttribArray(b);gl.vertexAttribPointer(b,c,d,!1,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,null)};var MeshManager=function(){this.list={};this.count=0};MeshManager.prototype.add=function(a){if(!(a instanceof Mesh))return console.error("MeshManager add() Error: "+typeof a+"is not Mesh"),null;a.uid=a.type+String(this.count);++this.count;this.list[a.uid]=a;return a.uid};MeshManager.prototype.delete=function(a){if(!this.list[a])return console.error("MeshManager delete() Error: "+a+" doesn't exist in list"),null;gl.deleteBuffer(this.list[a].vid);delete this.list[a]};
MeshManager.prototype.get=function(a){return this.list[a]?this.list[a]:(console.warn("MeshManager get() Warn: "+a+"Not found"),null)};MeshManager.prototype.getMeshNames=function(){return Object.keys(this.list)};MeshManager.prototype.reset=function(){for(var a in this.list)this.delete(a)};MeshManager.prototype.isEmpty=function(){return 0===Object.keys(this.list).length};var uniformType=Object.freeze({INT:0,FLOAT:1,VEC2:2,VEC3:3,VEC4:4,MAT3:5,MAT4:6}),Renderer=function(){this.uniform={};gl.useProgram(m_shader.program);this.projection=projection(width,height)};
Renderer.prototype.draw=function(){var a=this;gl.viewport(0,0,width,height);gl.clearColor(.2,.2,.2,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);m_mesh.getMeshNames().forEach(function(b){var c=gl.TRIANGLES;b=m_mesh.get(b);b.isLine&&(c=gl.LINES);m_shader.bindAttrib(b.vid,0,3,gl.FLOAT);var d=multiply(multiply(b.matrix,b.smatrix),b.rmatrix);a.bindUniform("MAT4","uMatrix",d);a.bindUniform("VEC4","uColor",b.color);"curve"===b.type?gl.drawArrays(gl.LINE_STRIP,0,b.vlen):2<=b.ipts.length&&(gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,
b.iid),gl.drawElements(c,b.ipts.length,gl.UNSIGNED_SHORT,0),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,null))})};Renderer.prototype.findUniform=function(a){var b=this;a.forEach(function(c){b.uniform[c]=gl.getUniformLocation(m_shader.program,c)})};
Renderer.prototype.bindUniform=function(a,b,c){var d=this.uniform[b];if(d)switch(uniformType[a]){case uniformType.INT:case uniformType.FLOAT:case uniformType.VEC2:case uniformType.VEC3:break;case uniformType.VEC4:gl.uniform4fv(d,new Float32Array(c));break;case uniformType.MAT3:break;case uniformType.MAT4:gl.uniformMatrix4fv(d,!1,c);break;default:console.error("bindUniform() Error: Unknown type: "+a)}else console.error("bindUniform() Error: Unknown uniform name "+b)};var Mesh=function(){this.type="Mesh";this.color=[1,0,0,1];this.matrix=identity();this.smatrix=identity();this.rmatrix=identity();this.ipts=this.vpts=null};Mesh.prototype.init=function(){this.vpts&&(this.vid||(this.vid=gl.createBuffer()),this.bindData(gl.ARRAY_BUFFER,this.vid,new Float32Array(this.vpts)));this.ipts&&(this.iid||(this.iid=gl.createBuffer()),this.bindData(gl.ELEMENT_ARRAY_BUFFER,this.iid,new Uint16Array(this.ipts)))};
Mesh.prototype.bindData=function(a,b,c){gl.bindBuffer(a,b);gl.bufferData(a,c,gl.STATIC_DRAW);gl.bindBuffer(a,null)};Mesh.prototype.setValues=function(a){var b=this;a&&Object.keys(a).forEach(function(c){b[c]=a[c]})};var Triangle=function(a){Mesh.call(this);this.type="triangle";this.vpts=[-12,13.48,0,12,13.48,0,0,-13.48,0];this.ipts=[0,1,2];this.vlen=this.vpts.length/3;this.setValues(a);this.init()};$jscomp.inherits(Triangle,Mesh);
var Rectangle=function(a){Mesh.call(this);this.type="rectangle";this.height=this.width=50;this.ipts=[0,1,2,2,3,0];this.vlen=4;this.setValues(a);this.vpts=this.createpts(this.width,this.height);this.init()};$jscomp.inherits(Rectangle,Mesh);Rectangle.prototype.createpts=function(a,b){return[0,0,0,a,0,0,a,b,0,0,b,0]};
var Polygon=function(a){Mesh.call(this);this.type="polygon";this.center=[0,0,0];this.radius=10;this.edgeCnt=5;this.setValues(a);a=this.radius_based_polygon(this.center,this.radius,this.edgeCnt);this.vpts=a.vpts;this.ipts=a.ipts;this.vlen=this.vpts.length/3;this.init()};$jscomp.inherits(Polygon,Mesh);
Polygon.prototype.radius_based_polygon=function(a,b,c){var d=360/c,e=[];e.push.apply(e,$jscomp.arrayFromIterable(a));for(var f=0;f<c;f++){var g=f*d*Math.PI/180;e.push(b*Math.cos(g)+a[0],b*Math.sin(g)+a[1],a[2])}a=[];for(b=1;b<c;b++)a.push(b+1,b,0);a.push(1,c,0);return{vpts:e,ipts:a}};var Circle=function(a){Polygon.call(this,Object.assign({},a,{edgeCnt:32}));this.type="circle"};$jscomp.inherits(Circle,Polygon);
var Line=function(a){Mesh.call(this);this.type="line";this.isLine=!0;this.vpts=[0,0,0];this.ipts=[0];this.vlen=this.vpts.length/3;this.setValues(a);this.init()};$jscomp.inherits(Line,Mesh);Line.prototype.movePts=function(a,b){var c=this.vlen-1;this.vpts[3*c]=a;this.vpts[3*c+1]=b;this.bindData(gl.ARRAY_BUFFER,this.vid,new Float32Array(this.vpts))};
Line.prototype.newPts=function(a,b){2>this.vlen?(this.movePts(a,b),this.vpts.push(a,b,0),this.ipts.push(1),this.bindData(gl.ARRAY_BUFFER,this.vid,new Float32Array(this.vpts)),this.bindData(gl.ELEMENT_ARRAY_BUFFER,this.iid,new Uint16Array(this.ipts)),this.vlen++):this.done=!0};var Polyline=function(a){Line.call(this,a);this.type="polyline";this.ipts=[];this.setValues(a)};$jscomp.inherits(Polyline,Line);
Polyline.prototype.newPts=function(a,b){this.movePts(a,b);this.vpts.push(a,b,0);this.bindData(gl.ARRAY_BUFFER,this.vid,new Float32Array(this.vpts));this.ipts.push(this.vlen-1,this.vlen);this.bindData(gl.ELEMENT_ARRAY_BUFFER,this.iid,new Uint16Array(this.ipts));this.vlen++};var Curve=function(a){Mesh.call(this);this.type="curve";this.cpts=[0,0,0,20,50,0,40,50,0,100,100,0];this.seg=100;this.createCurve();this.init()};$jscomp.inherits(Curve,Mesh);
Curve.prototype.init=function(){this.vpts&&(this.vid||(this.vid=gl.createBuffer()),this.bindData(gl.ARRAY_BUFFER,this.vid,new Float32Array(this.vpts)))};
Curve.prototype.createCurve=function(){var a=this.cpts.slice(0,3),b=this.cpts.slice(3,6),c=this.cpts.slice(6,9),d=this.cpts.slice(9,12),e=a[0],f=a[1],g=0,p=1/this.seg,k=[];k.push(e,f,0);for(i=1;i<this.seg;i++){g+=p;f=g*g;var m=f*g,h=1-g,l=h*h,n=l*h;e=n*a[0]+3*g*l*b[0]+3*f*h*c[0]+m*d[0];f=n*a[1]+3*g*l*b[1]+3*f*h*c[1]+m*d[1];k.push(e,f,0)}this.vlen=k.length/3;this.vpts=k};function select_mesh(a){var b=$(a);reset_selections($("#shapes"));reset_selections($("#transforms"));reset_selections($("#meshes"));reset_transformation();if(selected.type===a.className)selected.type="none";else{b.find("a").addClass("selected");selected.type=a.className;selected.isLine=!1;if("line"===selected.type||"polyline"===selected.type)selected.isLine=!0,selected.id=create_mesh(selected.type),selected.mesh=m_mesh.get(selected.id);"curve"===selected.type?($("#curve").removeClass("hide"),$("#curve").addClass("show")):
($("#curve").removeClass("show"),$("#curve").addClass("hide"))}}function add_mesh(a){$("#meshes").append('<li class="'+a+'"><a href="#"> '+a+" </a></li>");$("."+a).click(function(b){select_exist(b.currentTarget)})}function remove_mesh(){"exist"===selected.type&&(m_mesh.delete(selected.id),$("."+selected.id).remove(),selected.type="none")}
function select_tool(a){var b=$(a);reset_selections($("#shapes"));reset_selections($("#transforms"));b.find("a").addClass("selected");"none"!==selected.type&&"exist"!==selected.type&&(selected.type="none");reset_transformation();$("#"+a.className).removeClass("hide");$("#"+a.className).addClass("show")}function reset_transformation(){$("#transformationbox").children().each(function(a,b){$(b).hasClass("show")&&($(b).removeClass("show"),$(b).addClass("hide"))})}
function reset_selections(a){$(a).children().each(function(b,c){$(c).find("a").hasClass("selected")&&$(c).find("a").removeClass("selected")})}function open(){var a=this.files;reader=new FileReader;reader.onload=function(b){b=JSON.parse(b.target.result);read_meshes(b)};reader.readAsText(a[0])}function read_meshes(a){a.mesh.forEach(function(b){create_mesh(b.type,b)})}
function save(){var a={mesh:[]};m_mesh.getMeshNames().forEach(function(d){d=m_mesh.get(d);a.mesh.push(MeshClassToObject(d))});var b=document.createElement("a"),c=new Blob([JSON.stringify(a)],{type:"text/json"});b.href=URL.createObjectURL(c);b.download="shape_editor.json";b.click();b.remove()}function MeshClassToObject(a){var b={};Object.keys(a).forEach(function(c){b[c]=a[c]});delete b.uid;delete b.vid;delete b.iid;return b}
function exportImg(){var a=document.createElement("a");a.download="shape-editor.jpg";a.href=canvas.toDataURL("image/jpeg");a.click();a.remove()}function undo(){}function clear(){m_mesh.isEmpty()||confirm("It seems you scene is not empty, would you want to create new scene?")&&m_mesh.reset()};function select_exist(a){selected.isLine&&(m_mesh.delete(selected.id),selected.type="none",selected.id=null,selected.isLine=!1);selected.mesh=m_mesh.get(a.className);selected.mesh&&(console.log(a.className),reset_selections("#shapes"),reset_selections("#meshes"),$("."+a.className).find("a").addClass("selected"),selected.type="exist",selected.id=a.className)}
function create_mesh(a,b){switch(a){case "exist":case "none":break;case "line":return m_mesh.add(new Line(b));case "triangle":return m_mesh.add(new Triangle(b));case "rectangle":return m_mesh.add(new Rectangle(b));case "circle":return m_mesh.add(new Circle(b));case "curve":return m_mesh.add(new Curve(b));case "polyline":return m_mesh.add(new Polyline(b));case "polygon":return m_mesh.add(new Polygon(b));default:return console.warn("create_meshs() Warn: Unknown shape type "+a),null}};function mousedclick(a){"polyline"===selected.type&&(add_mesh(selected.id),selected.id=create_mesh(selected.type),selected.mesh=m_mesh.get(selected.id))}
function mouseup(a){0===a.button?"none"!==selected.type&&"exist"!==selected.type&&(selected.isLine?(selected.mesh.newPts(a.offsetX,a.offsetY),selected.mesh.done&&(add_mesh(selected.id),selected.id=create_mesh(selected.type),selected.mesh=m_mesh.get(selected.id))):(a=create_mesh(selected.type,{matrix:moveto(identity(),[a.offsetX,a.offsetY,0])}),add_mesh(a))):2===a.button&&"none"!==selected.type&&"exist"!==selected.type&&selected.id&&m_mesh.delete(selected.id)}
function mousemove(a){selected.isLine&&selected.mesh.movePts(a.offsetX,a.offsetY)};function moveX(a){"exist"===selected.type&&(selected.mesh.matrix=moveto(selected.mesh.matrix,[Number(a.target.value),selected.mesh.matrix[13],0]))}function moveY(a){"exist"===selected.type&&(selected.mesh.matrix=moveto(selected.mesh.matrix,[selected.mesh.matrix[12],Number(a.target.value),0]))}function rotate(a){"exist"===selected.type&&(a=Number(a.target.value),selected.mesh.rmatrix=rotateZ(identity(),a))}
function scaleX(a){"exist"===selected.type&&(a=Number(a.target.value),selected.mesh.smatrix=scale(identity(),[a,selected.mesh.smatrix[5],1]))}function scaleY(a){"exist"===selected.type&&(a=Number(a.target.value),selected.mesh.smatrix=scale(identity(),[selected.mesh.smatrix[0],a,1]))}function ctrlPt1X(a){}function ctrlPt1Y(a){}function ctrlPt2X(a){}function ctrlPt2Y(a){}
function color(a){"exist"===selected.type&&(console.log("chaning color"),a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a.target.value),selected.mesh.color=a?[parseInt(a[1],16)/255,parseInt(a[2],16)/255,parseInt(a[3],16)/255,1]:[1,1,1,1])};var gl,canvas,width,height,m_mesh,m_shader,m_renderer,selected={type:"none",created:!1,isLine:!1};function start(){console.log("start");setInterval(function(){m_renderer.draw()},25)};$(document).ready(function(){canvas=document.getElementById("canvas");console.log("Canvas size: "+canvas.clientWidth+" "+canvas.clientHeight);width=canvas.clientWidth;height=canvas.clientHeight;if(gl=canvas.getContext("webgl",{preserveDrawingBuffer:!0})){m_mesh=new MeshManager;m_shader=new Shader(vShader,fShader,["aPosition"]);m_renderer=new Renderer(m_shader,m_mesh);m_renderer.findUniform(["uColor","uProjMatrix","uMatrix"]);m_renderer.bindUniform("MAT4","uProjMatrix",m_renderer.projection);$("#shapebox").draggable({handle:"h3",
containment:"#container"});$("#toolbox").draggable({handle:"h3",containment:"#container"});$("#meshbox").draggable({handle:"h3",containment:"#container"});$("#transformationbox").draggable({handle:"h3",containment:"#container"});$("#colorbox").draggable({handle:"h3",containment:"#container"});$("li.line").click(function(f){select_mesh(f.currentTarget)});$("li.triangle").click(function(f){select_mesh(f.currentTarget)});$("li.rectangle").click(function(f){select_mesh(f.currentTarget)});$("li.circle").click(function(f){select_mesh(f.currentTarget)});
$("li.curve").click(function(f){select_mesh(f.currentTarget)});$("li.polyline").click(function(f){select_mesh(f.currentTarget)});$("li.polygon").click(function(f){select_mesh(f.currentTarget)});document.getElementById("fileinput").addEventListener("change",open);$("li.new").click(function(f){clear()});$("li.save").click(function(f){save()});$("li.export").click(function(f){exportImg()});$("li.undo").click(function(f){});$("li.delete").click(function(f){remove_mesh()});$("li.move").click(function(f){select_tool(f.currentTarget)});
$("li.scale").click(function(f){select_tool(f.currentTarget)});$("li.rotate").click(function(f){select_tool(f.currentTarget)});document.getElementById("move-x").addEventListener("input",moveX);document.getElementById("move-y").addEventListener("input",moveY);document.getElementById("ctrl-1x").addEventListener("input",ctrlPt1X);document.getElementById("ctrl-1y").addEventListener("input",ctrlPt1Y);document.getElementById("ctrl-2x").addEventListener("input",ctrlPt2X);document.getElementById("ctrl-2y").addEventListener("input",
ctrlPt2Y);document.getElementById("scale-x").addEventListener("input",scaleX);document.getElementById("scale-y").addEventListener("input",scaleY);document.getElementById("rotateinput").addEventListener("input",rotate);for(var a=["move-x","ctrl-1x","ctrl-2x"],b=["move-y","ctrl-1y","ctrl-2y"],c=0;3>c;c++){var d=document.getElementById(a[c]),e=document.getElementById(b[c]);d.min=0;d.max=width;e.min=0;e.max=height}document.getElementById("color-picker").addEventListener("change",color);canvas.addEventListener("mousemove",
mousemove);canvas.addEventListener("mouseup",mouseup);canvas.addEventListener("dblclick",mousedclick);canvas.addEventListener("contextmenu",function(f){f.preventDefault();f.stopPropagation()});start()}else alert("Failed to get webgl context")});
