var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;
$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===$jscomp.propertyToPolyfillSymbol[e]&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):
$jscomp.POLYFILL_PREFIX+e),$jscomp.defineProperty(d,$jscomp.propertyToPolyfillSymbol[e],{configurable:!0,writable:!0,value:b})))};
$jscomp.getConstructImplementation=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if($jscomp.TRUST_ES6_POLYFILLS&&"undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=$jscomp.objectCreate(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||
e}};$jscomp.construct={valueOf:$jscomp.getConstructImplementation}.valueOf();$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.inherits=function(a,b){a.prototype=$jscomp.objectCreate(b.prototype);a.prototype.constructor=a;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(a,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.superClass_=b.prototype};$jscomp.polyfill("Reflect",function(a){return a?a:{}},"es6","es3");$jscomp.polyfill("Reflect.construct",function(a){return $jscomp.construct},"es6","es3");
$jscomp.polyfill("Reflect.setPrototypeOf",function(a){if(a)return a;if($jscomp.setPrototypeOf){var b=$jscomp.setPrototypeOf;return function(c,d){try{return b(c,d),!0}catch(e){return!1}}}return null},"es6","es5");$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(e,f){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:f})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(e){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(e||"")+"_"+c++,e)};return d},"es6","es3");
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};$jscomp.polyfill("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)$jscomp.owns(b,d)&&c.push(b[d]);return c}},"es8","es3");$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(b,c){return $jscomp.findInternal(this,b,c).v}},"es6","es3");function projection(a,b,c){return[2/a,0,0,0,0,-2/b,0,0,0,0,2/(void 0===c?400:c),0,-1,1,0,1]}function identity(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}function translation(a){return[1,0,0,0,0,1,0,0,0,0,1,0,a[0],a[1],a[2],1]}function translate(a,b){return multiply(a,translation(b))}function moveto(a,b){a[12]=0;a[13]=0;a[14]=0;return translate(a,b)}
function rotateZ(a,b){var c=degToRad(b);b=Math.cos(c);c=Math.sin(c);return multiply(a,[b,c,0,0,-c,b,0,0,0,0,1,0,0,0,0,1])}function degToRad(a){return a*Math.PI/180}function scale(a,b){return multiply(a,[b[0],0,0,0,0,b[1],0,0,0,0,b[2],0,0,0,0,1])}
function multiply(a,b){var c=a[0],d=a[1],e=a[2],f=a[3],g=a[4],h=a[5],k=a[6],l=a[7],m=a[8],n=a[9],p=a[10],q=a[11],r=a[12],t=a[13],u=a[14];a=a[15];var v=b[0],w=b[1],x=b[2],y=b[3],z=b[4],A=b[5],B=b[6],C=b[7],D=b[8],E=b[9],F=b[10],G=b[11],H=b[12],I=b[13],J=b[14];b=b[15];return[v*c+w*g+x*m+y*r,v*d+w*h+x*n+y*t,v*e+w*k+x*p+y*u,v*f+w*l+x*q+y*a,z*c+A*g+B*m+C*r,z*d+A*h+B*n+C*t,z*e+A*k+B*p+C*u,z*f+A*l+B*q+C*a,D*c+E*g+F*m+G*r,D*d+E*h+F*n+G*t,D*e+E*k+F*p+G*u,D*f+E*l+F*q+G*a,H*c+I*g+J*m+b*r,H*d+I*h+J*n+b*t,H*e+
I*k+J*p+b*u,H*f+I*l+J*q+b*a]}function MultiplyMatrix4(a,b){if(4!==b.length)return console.warn("MultiplyMatrix4 Error, vec length is not 4"),a;var c=b[0],d=b[1],e=b[2];b=b[3];return[(a[0]*c+a[4]*d+a[8]*e+a[12])*b,(a[1]*c+a[5]*d+a[9]*e+a[13])*b,(a[2]*c+a[6]*d+a[10]*e+a[14])*b,(a[3]*c+a[7]*d+a[11]*e+a[15])*b]};var Vector4=function(a,b,c,d){this.x=void 0===a?0:a;this.y=void 0===b?0:b;this.z=void 0===c?0:c;this.w=void 0===d?1:d;this.vector=!0};Vector4.prototype.toArray=function(){return[this.x,this.y,this.z,this.w]};Vector4.prototype.clone=function(){return(new Vector4).copy(this)};Vector4.prototype.setAll=function(a,b,c,d){this.x=a;this.y=b;this.z=c;this.w=d;return this};
Vector4.prototype.set=function(a,b){switch(a){case "x":this.x=b;break;case "y":this.y=b;break;case "z":this.z=b;break;case "w":this.w=b;break;default:console.error("Vector4 set() Error: Unkown type: "+a)}};Vector4.prototype.copy=function(a){this.x=a.x;this.y=a.y;this.z=a.z;this.w=a.w;return this};
Vector4.prototype.multiplyMatrix4=function(a){var b=this.x,c=this.y,d=this.z,e=this.w;this.x=(a[0]*b+a[4]*c+a[8]*d+a[12])*e;this.y=(a[1]*b+a[5]*c+a[9]*d+a[13])*e;this.z=(a[2]*b+a[6]*c+a[10]*d+a[14])*e;this.w=(a[3]*b+a[7]*c+a[11]*d+a[15])*e};var Vector3=function(a,b,c){this.x=void 0===a?0:a;this.y=void 0===b?0:b;this.z=void 0===c?0:c;this.vector=!0};Vector3.prototype.toArray=function(){return[this.x,this.y,this.z]};Vector3.prototype.clone=function(){return(new Vector3).copy(this)};
Vector3.prototype.setAll=function(a,b,c){this.x=a;this.y=b;this.z=c;return this};Vector3.prototype.set=function(a,b){switch(a){case "x":this.x=b;break;case "y":this.y=b;break;case "z":this.z=b;break;default:console.error("Vector4 set() Error: Unkown type: "+a)}};Vector3.prototype.copy=function(a){this.x=a.x;this.y=a.y;this.z=a.z;return this};
Vector3.prototype.multiplyMatrix4=function(a){var b=this.x,c=this.y,d=this.z,e=1/(a[3]*b+a[7]*c+a[11]*d+a[15]);this.x=(a[0]*b+a[4]*c+a[8]*d+a[12])*e;this.y=(a[1]*b+a[5]*c+a[9]*d+a[13])*e;this.z=(a[2]*b+a[6]*c+a[10]*d+a[14])*e;return this};var Mesh=function(){this.type="Mesh";this.attributes={color:new Vector4(1,0,0,1),p_matrix:identity(),r_matrix:identity(),s_matrix:identity()};this.position={};this.index={};this.m=!0};Mesh.prototype.setAttribute=function(a,b){this.attributes[a]=b;this.m=!0};Mesh.prototype.getAttribute=function(a){return this.attributes[a]};Mesh.prototype.applyMatrix=function(a,b){this.attributes[a]=multiply(this.attributes[a],b);this.m=!0};
Mesh.prototype.updatePosition=function(a){for(var b=this.position,c=b.points,d=0;d<b.length;d++){var e=MultiplyMatrix4(a,[c[3*d],c[3*d+1],c[3*d+2],1]);c[3*d]=e[0];c[3*d+1]=e[1];c[3*d+2]=e[2]}this.m=!0};Mesh.prototype.clone=function(){return(new Mesh).copy(this)};
Mesh.prototype.copy=function(a){this.type=a.type;a.index&&(this.index.points=new (Function.prototype.bind.apply(Array,[null].concat($jscomp.arrayFromIterable(a.index.points)))));a.position&&(this.position.points=new (Function.prototype.bind.apply(Array,[null].concat($jscomp.arrayFromIterable(a.position.points)))),this.position.length=a.position.length);a=a.attributes;for(var b in a){var c=a[b];c&&(c.clone?this.attributes[b]=c.clone():Array.isArray(c)?this.attributes[b]=new (Function.prototype.bind.apply(Array,
[null].concat($jscomp.arrayFromIterable(c)))):this.attributes[b]=c.vector?new Vector4(c.x,c.y,c.z,c.w?c.w:1):c)}this.m=!0;return this};Mesh.prototype.delete=function(){gl.deleteBuffer(this.position.id);gl.deleteBuffer(this.index.id);this.type="Mesh";this.attributes={};this.position={};this.index={};this.m=!0};
Mesh.prototype.bindBuffer=function(){var a=this.position;a.points&&(a.id||(a.id=gl.createBuffer()),gl.bindBuffer(gl.ARRAY_BUFFER,a.id),gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(a.points),gl.STATIC_DRAW),gl.bindBuffer(gl.ARRAY_BUFFER,null))};
Mesh.prototype.bindIndexBuffer=function(){var a=this.index;a.points&&(a.id||(a.id=gl.createBuffer()),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,a.id),gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(a.points),gl.STATIC_DRAW),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,null))};var Triangle=function(a,b,c){Mesh.call(this);this.type="triangle";this.position.points=[].concat($jscomp.arrayFromIterable(a.toArray()),$jscomp.arrayFromIterable(b.toArray()),$jscomp.arrayFromIterable(c.toArray()));this.position.length=3;this.index.points=[0,1,2];this.updatePosition(translation([0,-b.y/2,0,1]));this.bindBuffer();this.bindIndexBuffer()};$jscomp.inherits(Triangle,Mesh);
Triangle.prototype.clone=function(){return(new Triangle(new Vector3(-10,0,0),new Vector3(0,-15,0),new Vector3(10,0,0))).copy(this)};var Rectangle=function(a,b){a=void 0===a?50:a;b=void 0===b?50:b;Mesh.call(this);this.type="rectangle";this.position.points=[0,0,0,a,0,0,a,b,0,0,b,0];this.position.length=4;this.index.points=[0,1,2,2,3,0];this.attributes.width=a;this.attributes.height=b;this.updatePosition(translation([-a/2,-b/2,0,1]));this.bindBuffer();this.bindIndexBuffer()};
$jscomp.inherits(Rectangle,Mesh);Rectangle.prototype.clone=function(){return(new Rectangle(15,15)).copy(this)};var Polygon=function(a,b,c){Mesh.call(this);this.type="polygon";this.attributes.center=a;this.attributes.radius=b;this.attributes.edgeCnt=c;a=this.radius_based_polygon(a.toArray(),b,c);this.position.points=a.position;this.position.length=a.position.length/3;this.index.points=a.index;this.outlineIndex={points:a.outline};this.bindBuffer();this.bindIndexBuffer();this.bindOutIndex()};
$jscomp.inherits(Polygon,Mesh);Polygon.prototype.bindOutIndex=function(){var a=this.outlineIndex;a.points&&(a.id||(a.id=gl.createBuffer()),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,a.id),gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(a.points),gl.STATIC_DRAW),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,null))};
Polygon.prototype.changeEdgeCnt=function(a){this.attributes.edgeCnt=a;a=this.radius_based_polygon(this.attributes.center,this.attributes.radius,edgCnt);this.position.points=a.position;this.position.length=a.position.length/3;this.index.points=a.index;this.m=!0};
Polygon.prototype.radius_based_polygon=function(a,b,c){var d=360/c,e=[];e.push.apply(e,$jscomp.arrayFromIterable(a));for(var f=0;f<c;f++){var g=f*d*Math.PI/180;e.push(b*Math.cos(g)+a[0],b*Math.sin(g)+a[1],a[2])}a=[];b=[];for(d=1;d<c;d++)a.push(d+1,d,0),b.push(d,d+1);a.push(1,c,0);b.push(c,1);return{position:e,index:a,outline:b}};Polygon.prototype.clone=function(){return(new Polygon(new Vector3(0,0,0),12,5)).copy(this)};
Polygon.prototype.delete=function(){Mesh.prototype.delete.call(this);gl.deleteBuffer(this.outlineIndex.id);this.outlineIndex={}};var Circle=function(a,b){Polygon.call(this,a,void 0===b?10:b,32);this.type="circle"};$jscomp.inherits(Circle,Polygon);Circle.prototype.clone=function(){return(new Circle(new Vector3(0,0,0),12)).copy(this)};
var Line=function(){Mesh.call(this);this.type="line";this.isLine=!0;this.attributes.lineCnt=1;this.attributes.maxCnt=2;this.position.points=[0,0,0,0,0,0];this.position.length=2;this.index.points=[0,1];this.ctrlPts=this.index;this.bindBuffer();this.bindIndexBuffer()};$jscomp.inherits(Line,Mesh);Line.prototype.movePts=function(a,b){var c=this.position.points;c[3*a]=b.x;c[3*a+1]=b.y;c[3*a+2]=b.z;this.bindBuffer()};Line.prototype.clone=function(){return(new Line).copy(this)};
Line.prototype.copy=function(a){Mesh.prototype.copy.call(this,a);this.bindBuffer();this.bindIndexBuffer();return this};var Polyline=function(){Line.call(this);this.type="polyline";this.attributes.maxCnt=Infinity};$jscomp.inherits(Polyline,Line);
Polyline.prototype.newLine=function(a){this.position.points.push.apply(this.position.points,$jscomp.arrayFromIterable(a.toArray()));this.position.length++;a=this.attributes.lineCnt;this.index.points.push(a,a+1);this.setAttribute("lineCnt",a+1);this.bindBuffer();this.bindIndexBuffer();return this.attributes.lineCnt};Polyline.prototype.clone=function(){return(new Polyline).copy(this)};Polyline.prototype.copy=function(a){Line.prototype.copy.call(this,a);this.bindBuffer();this.bindIndexBuffer();return this};
var Curve=function(){Polyline.call(this);this.type="curve";this.attributes.segment=10;this.init=!0;this.ctrlPts={points:[],cPoints:[]}};$jscomp.inherits(Curve,Polyline);Curve.prototype.bindCtrlPtsBuffer=function(){var a=this.ctrlPts;a.points&&(a.id||(a.id=gl.createBuffer()),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,a.id),gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(a.points),gl.STATIC_DRAW),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,null))};Curve.prototype.clone=function(){return(new Curve).copy(this)};
Curve.prototype.copy=function(a){var b=this;Polyline.prototype.copy.call(this,a);a.ctrlPts&&(this.ctrlPts.points=new (Function.prototype.bind.apply(Array,[null].concat($jscomp.arrayFromIterable(a.ctrlPts.points)))),a.ctrlPts.cPoints.forEach(function(c){b.ctrlPts.cPoints.push(new Vector3(c.x,c.y,c.z))}),this.createCurve(),this.bindBuffer(),this.bindIndexBuffer(),this.bindCtrlPtsBuffer());return this};
Curve.prototype.newLine=function(a){2<this.ctrlPts.cPoints.length?(this.createCurve(),this.attributes.lineCnt++,this.bindBuffer(),this.bindIndexBuffer(),this.bindCtrlPtsBuffer()):Polyline.prototype.newLine.call(this,a)};Curve.prototype.movePts=function(a,b){this.ctrlPts.cPoints[a]=b.clone();2<this.ctrlPts.cPoints.length?(this.createCurve(),this.bindBuffer(),this.bindIndexBuffer(),this.bindCtrlPtsBuffer()):Polyline.prototype.movePts.call(this,a,b)};
Curve.prototype.createCurve=function(){for(var a=this.ctrlPts.cPoints.slice(),b=a.length-1;0<b;b--){var c=a[b],d=a[b-1];1>Math.sqrt((d.x-c.x)*(d.x-c.x)+(d.y-c.y)*(d.y-c.y))&&a.splice(b,1)}c=a.length;if(!(2>c)){b=new Vector3(2*a[0].x-a[1].x,2*a[0].y-a[1].y);c=new Vector3(2*a[c-1].x-a[c-2].x,2*a[c-1].y-a[c-2].y);a.splice(0,0,b);a.push(c);b=this.position.points=[];c=this.index.points=[];d=this.ctrlPts.points=[0];for(var e=this.getAttribute("segment"),f=1;f<a.length-2;f++){var g=a[f-1],h=a[f],k=a[f+1],
l=a[f+2];b.push(a[f].x,a[f].y,0);for(var m=1;m<e;m++){var n=m/e,p=n*n,q=p*n;b.push(.5*(2*h.x+(-g.x+k.x)*n+(2*g.x-5*h.x+4*k.x-l.x)*p+(-g.x+3*h.x-3*k.x+l.x)*q),.5*(2*h.y+(-g.y+k.y)*n+(2*g.y-5*h.y+4*k.y-l.y)*p+(-g.y+3*h.y-3*k.y+l.y)*q),0);c.push((f-1)*e+m-1,(f-1)*e+m)}c.push(e*f-1,e*f);d.push(f*e-1)}c.pop();this.position.length=b.length/3}};var fShader="\nprecision mediump float;\nvarying vec4 vColor;\nvoid main(){\n    gl_FragColor = vColor;\n}";var vShader="\nattribute vec4 aPosition;\nuniform vec4 uColor;\nuniform mat4 uMatrix;\nvarying vec4 vColor;\nvoid main(){\n    gl_Position = uMatrix * aPosition;\n    vColor = uColor;\n}",vDotShader="\nattribute vec4 aPosition;\nuniform vec4 udColor;\nuniform mat4 uMatrix;\nvarying vec4 vColor;\nvoid main(){\n    gl_Position = uMatrix * aPosition;\n    gl_PointSize = 5.0;\n    vColor = udColor;\n}";var Shader=function(a,b,c,d){var e=this;a=this.createShader(gl.VERTEX_SHADER,a);b=this.createShader(gl.FRAGMENT_SHADER,b);if(!a||!b)return null;var f=gl.createProgram();gl.attachShader(f,a);gl.attachShader(f,b);c.forEach(function(g,h){gl.bindAttribLocation(f,h,g)});gl.linkProgram(f);this.uniform={};d.forEach(function(g){e.uniform[g]=gl.getUniformLocation(f,g)});this.program=f};
Shader.prototype.createShader=function(a,b){var c=gl.createShader(a);gl.shaderSource(c,b);gl.compileShader(c);return gl.getShaderParameter(c,gl.COMPILE_STATUS)?c:(b=gl.getShaderInfoLog(c),console.error("Shader createShader() Error: Failed to compile "+a+". "+b),gl.deleteShader(c),null)};Shader.prototype.bindAttrib=function(a,b,c,d){gl.bindBuffer(gl.ARRAY_BUFFER,a);gl.enableVertexAttribArray(b);gl.vertexAttribPointer(b,c,d,!1,0,0);gl.bindBuffer(gl.ARRAY_BUFFER,null)};
Shader.prototype.bindUniform=function(a,b,c){var d=this.uniform[b];if(d)switch(uniformType[a]){case uniformType.INT:case uniformType.FLOAT:case uniformType.VEC2:case uniformType.VEC3:break;case uniformType.VEC4:gl.uniform4fv(d,new Float32Array(c));break;case uniformType.MAT3:break;case uniformType.MAT4:gl.uniformMatrix4fv(d,!1,c);break;default:console.error("bindUniform() Error: Unknown type: "+a)}else console.error("bindUniform() Error: Unknown uniform name "+b)};var MeshManager=function(){this.list={};this.count=0;this.selected=[]};MeshManager.prototype.add=function(a){if(!(a instanceof Mesh))return console.error("MeshManager add() Error: "+typeof a+" is not Mesh"),null;a.uid=a.type+String(this.count);++this.count;this.list[a.uid]=a;return a.uid};MeshManager.prototype.delete=function(a){if(!this.list[a])return console.error("MeshManager delete() Error: "+a+" doesn't exist in list"),null;this.list[a].delete();delete this.list[a]};
MeshManager.prototype.get=function(a){return this.list[a]?this.list[a]:(console.warn("MeshManager get() Warn: "+a+"Not found"),null)};MeshManager.prototype.getAllNames=function(){return Object.keys(this.list)};MeshManager.prototype.getAllMeshes=function(){return Object.values(this.list)};MeshManager.prototype.reset=function(){for(var a in this.list)this.delete(a)};MeshManager.prototype.isEmpty=function(){return 0===Object.keys(this.list).length};
MeshManager.prototype.create=function(a){switch(a){case "triangle":return this.add(new Triangle(new Vector3(-10,0,0),new Vector3(0,-15,0),new Vector3(10,0,0)));case "rectangle":return this.add(new Rectangle(15,15));case "polygon":return this.add(new Polygon(new Vector3(0,0,0),12,5));case "circle":return this.add(new Circle(new Vector3(0,0,0),12));case "line":return this.add(new Line);case "curve":return this.add(new Curve);case "polyline":return this.add(new Polyline);default:return console.error("Meshmanger Create Error: Unknown shape type "+
a),null}};var uniformType=Object.freeze({INT:0,FLOAT:1,VEC2:2,VEC3:3,VEC4:4,MAT3:5,MAT4:6}),Renderer=function(){this.uniform={};gl.useProgram(m_shader.program);this.projection=projection(width,height);this.p_matrix=identity();this.r_matrix=identity();this.s_matrix=identity();this.b_color=new Vector4(.2,.2,.2,1)};
Renderer.prototype.draw=function(){var a=this;gl.viewport(0,0,width,height);gl.clearColor.apply(gl,$jscomp.arrayFromIterable(this.b_color.toArray()));gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);var b=!1;m_mesh.getAllNames().forEach(function(c){var d=m_mesh.get(c);d.m&&(b=!0,d.m=!1);var e=gl.TRIANGLES;d.isLine&&(e=gl.LINE_STRIP);m_shader.bindAttrib(d.position.id,0,3,gl.FLOAT);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,d.index.id);gl.bindBuffer(gl.ARRAY_BUFFER,d.position.id);var f=d.getAttribute("p_matrix"),
g=d.getAttribute("r_matrix"),h=d.getAttribute("s_matrix");m_shader.bindUniform("VEC4","uColor",d.attributes.color.toArray());m_select.exist(c)?(c=multiply(multiply(multiply(a.projection,multiply(a.p_matrix,f)),multiply(a.r_matrix,g)),multiply(a.s_matrix,h)),m_shader.bindUniform("MAT4","uMatrix",c),gl.drawElements(e,d.index.points.length,gl.UNSIGNED_SHORT,0),d instanceof Polygon?(m_shader.bindUniform("VEC4","uColor",[0,0,0,1]),gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,d.outlineIndex.id),gl.drawElements(gl.LINE_LOOP,
d.outlineIndex.points.length,gl.UNSIGNED_SHORT,0)):d.isLine?(gl.useProgram(m_dot_shader.program),m_dot_shader.bindAttrib(d.position.id,0,3,gl.FLOAT),gl.bindBuffer(gl.ARRAY_BUFFER,d.position.id),e=d.index.points.length,"curve"===d.type&&(gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,d.ctrlPts.id),e=d.ctrlPts.points.length),m_dot_shader.bindUniform("MAT4","uMatrix",c),m_dot_shader.bindUniform("VEC4","udColor",[0,0,0,1]),gl.drawElements(gl.POINTS,e,gl.UNSIGNED_SHORT,0),gl.useProgram(m_shader.program)):(m_shader.bindUniform("VEC4",
"uColor",[0,0,0,1]),gl.drawElements(gl.LINE_LOOP,d.index.points.length,gl.UNSIGNED_SHORT,0))):(c=multiply(multiply(multiply(a.projection,f),g),h),m_shader.bindUniform("MAT4","uMatrix",c),gl.drawElements(e,d.index.points.length,gl.UNSIGNED_SHORT,0));gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,null);gl.bindBuffer(gl.ARRAY_BUFFER,null)});b&&m_undo.push(m_mesh)};Renderer.prototype.resetMatrix=function(){this.p_matrix=identity();this.r_matrix=identity();this.s_matrix=identity()};var SelectionManager=function(){this.list=[]};SelectionManager.prototype.add=function(a){this.list.push(a)};SelectionManager.prototype.remove=function(a){this.list=this.list.filter(function(b){return b!==a})};SelectionManager.prototype.removeAll=function(){this.list=[]};SelectionManager.prototype.isEmpty=function(){return 0===this.list.length};SelectionManager.prototype.exist=function(a){return-1!==this.list.indexOf(a)};var UndoManager=function(){this.snapshot=[]};UndoManager.prototype.push=function(){var a={mesh:[]};m_mesh.getAllMeshes().forEach(function(b){a.mesh.push(MeshClassToObject(b))});this.snapshot.push(JSON.stringify(a))};UndoManager.prototype.pop=function(){return 1>=this.snapshot.length?JSON.parse(this.snapshot[0]):JSON.parse(this.snapshot.pop())};var UIManager=function(){this.selected="none";this.shapelist="triangle rectangle polygon circle line polyline curve".split(" ");this.transformlist=["move","scale","rotate"]};UIManager.prototype.clear=function(){$("#shapes").children().each(function(a,b){$(b).find("a").hasClass("selected")&&$(b).find("a").removeClass("selected")});$("#transforms").children().each(function(a,b){$(b).find("a").hasClass("selected")&&$(b).find("a").removeClass("selected")})};
UIManager.prototype.select=function(a){if(a===this.selected||"none"===a)this.clear(),this.selected="none",this.isTransformSelected=this.isShapeSelected=!1;else{var b=null;-1!==this.shapelist.indexOf(a)?(b=$("#shapes").children("."+a),this.isShapeSelected=!0,this.isTransformSelected=!1):-1!==this.transformlist.indexOf(a)?(b=$("#transforms").children("."+a),this.isShapeSelected=!1,this.isTransformSelected=!0):console.error("UIManager select() Error: "+a+" Not Found.");this.clear();b&&b.find("a").addClass("selected");
this.selected=a}};function move_m(a,b){m_renderer.p_matrix=translation([a,b,0])}function scale_m(a,b){m_renderer.s_matrix=scale(identity(),[a/20,b/20,1])}function rotate_m(a,b){b=Math.sqrt(a*a+b*b);0>a&&(b*=-1);m_renderer.r_matrix=rotateZ(identity(),b/4)}
function color(a){var b=(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(a.target.value))?[parseInt(a[1],16)/255,parseInt(a[2],16)/255,parseInt(a[3],16)/255,1]:[1,1,1,1];m_select.isEmpty()?m_renderer.b_color.setAll.apply(m_renderer.b_color,$jscomp.arrayFromIterable(b)):m_select.list.forEach(function(c){m_mesh.get(c).setAttribute("color",new (Function.prototype.bind.apply(Vector4,[null].concat($jscomp.arrayFromIterable(b)))))})};function open(){var a=this.files;reader=new FileReader;reader.onload=function(b){b=JSON.parse(b.target.result);read_meshes(b)};reader.readAsText(a[0])}function read_meshes(a){a.mesh.forEach(function(b){var c=m_mesh.create(b.type);delete b.position.id;delete b.index.id;b.ctrlPts&&delete b.ctrlPts.id;m_mesh.get(c).copy(b)})}
function saveJSON(){var a={mesh:[]};m_mesh.getAllMeshes().forEach(function(d){d=MeshClassToObject(d);a.mesh.push(d)});var b=document.createElement("a"),c=new Blob([JSON.stringify(a)],{type:"text/json"});b.href=URL.createObjectURL(c);b.download="shape_editor.json";b.click();b.remove()}function MeshClassToObject(a){var b={};Object.keys(a).forEach(function(c){b[c]=a[c]});return b}
function exportImg(){var a=document.createElement("a");a.download="shape-editor.jpg";a.href=canvas.toDataURL("image/jpeg");a.click();a.remove()}function undo(){m_undo.pop();var a=m_undo.pop();a&&(m_mesh.reset(),a.mesh.forEach(function(b){var c=m_mesh.create(b.type);m_mesh.get(c).copy(b)}))}var copiedlist=[];function copy(){copiedlist=new (Function.prototype.bind.apply(Array,[null].concat($jscomp.arrayFromIterable(m_select.list))))}
function paste(){m_select.removeAll();copiedlist.forEach(function(a){a=m_mesh.get(a).clone();a.applyMatrix("p_matrix",translation([5,5,0]));a.bindBuffer();a.bindIndexBuffer();a=m_mesh.add(a);m_select.add(a)})}function clear(){m_mesh.isEmpty()||confirm("It seems you scene is not empty, would you want to create new scene?")&&m_mesh.reset()};function mousedclick(a){line.creating&&2<=line.el.getAttribute("lineCnt")&&(line.creating=!1,line.el=null)}var pressFlag=!1,origin=new Vector3;function mousedown(a){pressFlag||!m_ui.isTransformSelected||m_select.isEmpty()||(origin.x=a.offsetX,origin.y=a.offsetY,pressFlag=!0)}var line={creating:!1,el:null};
function mouseup(a){if(0===a.button)if(line.creating){var b=line.el.getAttribute("lineCnt"),c=line.el.getAttribute("maxCnt");b+1>=c?(b++,line.creating=!1,line.el=null):b=line.el.newLine(new Vector3(a.offsetX,a.offsetY,0))}else if(m_ui.isShapeSelected)b=m_mesh.get(m_mesh.create(m_ui.selected)),b.isLine?(b.movePts(0,new Vector3(a.offsetX,a.offsetY,0)),line.creating=!0,line.el=b):b.setAttribute("p_matrix",translation([a.offsetX,a.offsetY,0]));else if(m_ui.isTransformSelected)pressFlag=!1,m_select.list.forEach(function(e){e=
m_mesh.get(e);e.applyMatrix("p_matrix",m_renderer.p_matrix);e.applyMatrix("r_matrix",m_renderer.r_matrix);e.applyMatrix("s_matrix",m_renderer.s_matrix)}),m_renderer.resetMatrix();else{var d=!1;m_mesh.getAllMeshes().forEach(function(e){if(e.isLine&&pointOnLine(e,[a.offsetX,a.offsetY])||pointOnPolygon(e,[a.offsetX,a.offsetY]))m_select.exist(e.uid)?m_select.remove(e.uid):m_select.add(e.uid),d=!0});d||m_select.removeAll()}}
function mousemove(a){if(line.creating)line.el.movePts(line.el.getAttribute("lineCnt"),new Vector3(a.offsetX,a.offsetY,0));else if(pressFlag){var b=a.offsetX-origin.x;a=a.offsetY-origin.y;switch(m_ui.selected){case "move":move_m(b,a);break;case "scale":scale_m(b,a);break;case "rotate":rotate_m(b,a);break;default:console.error("Mousemove Error: Invalid selected from UIManager: "+m_ui.selected),pressFlag=!1}}}
function pointOnPolygon(a,b){var c=a.clone();a=multiply(multiply(c.getAttribute("p_matrix"),c.getAttribute("r_matrix")),c.getAttribute("s_matrix"));c.updatePosition(a);a=c.position.points;c=c.position.length;var d=b[0];b=b[1];for(var e=!1,f=0,g=c-1;f<c;g=f++){var h=a[3*f],k=a[3*f+1],l=a[3*g];g=a[3*g+1];k>=b!==g>=b&&d<=(l-h)*(b-k)/(g-k)+h&&(e=!e)}return e}
function pointOnLine(a,b){var c=a.clone();a=multiply(multiply(c.getAttribute("p_matrix"),c.getAttribute("r_matrix")),c.getAttribute("s_matrix"));c.updatePosition(a);a=c.position.points;c=c.position.length;var d=b[0];b=b[1];for(var e=0;e<c-1;++e)for(var f=a[3*e],g=a[3*e+1],h=(a[3*(e+1)]-f)/50,k=(a[3*(e+1)+1]-g)/50,l=0;50>l;l++){f+=h;g+=k;var m=d-f,n=b-g;if(5>Math.sqrt(m*m+n*n))return!0}return!1};var gl,canvas,width,height,m_mesh,m_shader,m_dot_shader,m_renderer,m_undo,m_select,m_ui;function start(){console.log("start");setInterval(function(){m_renderer.draw()},25)};$(document).ready(function(){canvas=document.getElementById("canvas");canvas.width=width=canvas.clientWidth;canvas.height=height=canvas.clientHeight;console.log("Canvas size: "+width+" "+height);(gl=canvas.getContext("webgl",{preserveDrawingBuffer:!0}))?(m_mesh=new MeshManager,m_shader=new Shader(vShader,fShader,["aPosition"],["uColor","uMatrix"]),m_dot_shader=new Shader(vDotShader,fShader,["aPosition"],["udColor","uMatrix"]),m_renderer=new Renderer,m_select=new SelectionManager,m_ui=new UIManager,
m_undo=new UndoManager,m_undo.push(m_mesh),$("li.triangle").click(function(a){m_ui.select("triangle")}),$("li.rectangle").click(function(a){m_ui.select("rectangle")}),$("li.circle").click(function(a){m_ui.select("circle")}),$("li.curve").click(function(a){m_ui.select("curve")}),$("li.line").click(function(a){m_ui.select("line")}),$("li.polyline").click(function(a){m_ui.select("polyline")}),$("li.polygon").click(function(a){m_ui.select("polygon")}),document.getElementById("fileinput").addEventListener("change",
open),$("li.new").click(function(a){clear()}),$("li.save").click(function(a){saveJSON()}),$("li.export").click(function(a){exportImg()}),$("li.undo").click(function(a){undo()}),$("li.copy").click(function(a){copy()}),$("li.paste").click(function(a){paste()}),$("li.delete").click(function(a){m_select.list.forEach(function(b){m_mesh.delete(b)})}),$("li.move").click(function(a){m_ui.select("move")}),$("li.scale").click(function(a){m_ui.select("scale")}),$("li.rotate").click(function(a){m_ui.select("rotate")}),
document.getElementById("color-picker").addEventListener("input",color),canvas.addEventListener("mousemove",mousemove),canvas.addEventListener("mousedown",mousedown),canvas.addEventListener("mouseup",mouseup),canvas.addEventListener("dblclick",mousedclick),canvas.addEventListener("contextmenu",function(a){a.preventDefault();a.stopPropagation()}),document.addEventListener("keypress",function(a){switch(a.key){case "a":m_ui.select("none"),m_select.isEmpty()?m_mesh.getAllNames().forEach(function(b){m_select.add(b)}):
m_select.removeAll()}}),document.addEventListener("keydown",function(a){if(a.ctrlKey)switch(a.key){case "c":copy();break;case "v":paste()}else switch(a.key){case "Escape":m_ui.select("none");break;case "Delete":m_select.list.forEach(function(b){m_mesh.delete(b)})}}),start()):alert("Failed to get webgl context")});
